// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/registro": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Adiciona um novo registro no diário",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Evento ocorrido agora?",
                        "name": "ocorrido_agora",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Horário do evento",
                        "name": "horario_evento",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Quem está registrando?",
                        "name": "reporter",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Descrição do evento",
                        "name": "descricao",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.Record"
                        }
                    },
                    "400": {
                        "description": "insira dados faltantes",
                        "schema": {
                            "$ref": "#/definitions/web.APIError"
                        }
                    },
                    "500": {
                        "description": "falha na inserção de dados",
                        "schema": {
                            "$ref": "#/definitions/web.APIError"
                        }
                    }
                }
            }
        },
        "/registros": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Lista todos os registros",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Record"
                            }
                        }
                    }
                }
            }
        },
        "/relatorio": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Exibe relatório com contagem de convulsões registradas ao longo do dia",
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Record": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "event_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "regtime": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "web.APIError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:8080",
	BasePath:         "/diario",
	Schemes:          []string{},
	Title:            "MonitoLara - Diário de Crise",
	Description:      "Ferramenta simplificada para registro de crises de Lara",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
